apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tweetscraper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tweetscraper
        version: v0.7.8
    spec:
      containers:
      - name: tweetscraper
        image: chifamba/tweetscraper:0.7.8
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthCheck
            port: 8080
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 30

#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: tweetscraper
#  labels:
#    app: tweetscraper
#spec:
#  containers:
#  - name: tweetscraper
#    image: chifamba/tweetscraper:0.7.8
#    imagePullPolicy: IfNotPresent
#    livenessProbe:
#      httpGet:
#        path: /healthCheck
#        port: 8080
#        scheme: HTTPS
#      initialDelaySeconds: 60
#      periodSeconds: 30
#