---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    app: mongo
    mongo_node: mongo
spec:
  containers:
  - name: mongo
    image: mongo:3.4.14
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 27017
      name: mongo
    volumeMounts:
    - name: mongo-persistent-storage
      mountPath: /data/db
  volumes:
    - name: mongo-persistent-storage
      persistentVolumeClaim:
        claimName: mongo-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    mongo_node: mongo
  name: mongodb
spec:
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
  selector:
    mongo_node: mongo

