apiVersion: "apps/v1" # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: zeppelin
  labels:
     app: zeppelin
spec:
  serviceName: zeppelin
  replicas: 1
  selector:
    matchLabels:
      app: zeppelin
  template:
    metadata:
      labels:
        app: zeppelin
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: zeppelin
        image: chifamba/zepplin:0.7.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: zeppelin-ui
        resources:
          limits:
            cpu: "500m"
            memory: 4Gi
          requests:
           cpu: "100m"
           memory: 4Gi
        # These volume mounts are persistent. They are like inline claims,
        # but not exactly because the names need to match exactly one of
        # the stateful pod volumes.
        volumeMounts:
        - name: zeppelin-notebook
          mountPath: /opt/zeppelin/notebook
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  # do not use these in production until ssd GCEPersistentDisk or other ssd pd
  volumeClaimTemplates:
  - metadata:
      name: zeppelin-notebook
      annotations:
        volume.beta.kubernetes.io/storage-class: fast
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: docker.io/hostpath
parameters:
  type: pd-ssd
  
---
###########################################################################
# Ingress resource (gateway)
##########################################################################
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: gateway
#  annotations:
#    kubernetes.io/ingress.class: "istio"
#spec:
#   rules:
#   - http:
#       paths:
#       - path: /productpage
#         backend:
#           serviceName: productpage
#           servicePort: 9080
#       - path: /login
#         backend:
#           serviceName: productpage
#           servicePort: 9080
#       - path: /logout
#         backend:
#           serviceName: productpage
#           servicePort: 9080
#       - path: /api/v1/products.*
#         backend:
#           serviceName: productpage
#           servicePort: 9080
# ---
