apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    service: etcd
spec:
  ports:
  - name: etcd-client-port
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd

---
apiVersion: v1
kind: Pod
metadata:
  name: etcd0
  labels:
    app: etcd
    etcd_node: etcd0
spec:
  containers:
  - name: etcd0
    image: quay.io/coreos/etcd:v3.3.1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 2379
      name: client
    - containerPort: 2380
      name: server
    command:
     - /usr/local/bin/etcd 
     - --config-file
     - /data/config/etcd.conf.yml
    volumeMounts:
    - name: etcd0-config-volume
      mountPath: /data/config
    - name: etcd0-data-volume
      mountPath: /etcd/storage
  volumes:
    - name: etcd0-config-volume
      configMap:
        name: etcd0-config
    - name: etcd0-data-volume
      persistentVolumeClaim:
        claimName: etcd0-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd0
  name: etcd0
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    etcd_node: etcd0

---

apiVersion: v1
kind: Pod
metadata:
  name: etcd1
  labels:
    app: etcd
    etcd_node: etcd1
spec:
  containers:
  - name: etcd1
    image: quay.io/coreos/etcd:v3.3.1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 2379
      name: client
    - containerPort: 2380
      name: server
    command:
     - /usr/local/bin/etcd 
     - --config-file
     - /data/config/etcd.conf.yml
    volumeMounts:
    - name: etcd1-config-volume
      mountPath: /data/config
    - name: etcd1-data-volume
      mountPath: /etcd/storage
  volumes:
    - name: etcd1-config-volume
      configMap:
        name: etcd1-config
    - name: etcd1-data-volume
      persistentVolumeClaim:
        claimName: etcd1-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd1
  name: etcd1
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    etcd_node: etcd1

---

apiVersion: v1
kind: Pod
metadata:
  name: etcd2
  labels:
    app: etcd
    etcd_node: etcd2
spec:
  containers:
  - name: etcd2
    image: quay.io/coreos/etcd:v3.3.1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 2379
      name: client
    - containerPort: 2380
      name: server
    command:
     - /usr/local/bin/etcd 
     - --config-file
     - /data/config/etcd.conf.yml
    volumeMounts:
    - name: etcd2-config-volume
      mountPath: /data/config
    - name: etcd2-data-volume
      mountPath: /etcd/storage
  volumes:
    - name: etcd2-config-volume
      configMap:
        name: etcd2-config
    - name: etcd2-data-volume
      persistentVolumeClaim:
        claimName: etcd2-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd2
  name: etcd2
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    etcd_node: etcd2
